import sys
from .cmd_zonc import cmd_zon_run, cmd_zon_version, cmd_zon_help, cmd_zon_set_path, cmd_zon_show_path, cmd_zon_clear_path
from .cmd_zonc import cmd_zon_set_file
from zonc.utils import levenshtein_zon

commands = {
        "help":     "Show this help message or info about a specific command.",
        "r|run":    "Execute a Zonetic program file (.zon).",
        "vers":     "Show Zonny's greeting and the current version info.",
        "setpath":  "Set a global directory to look for .zon files.",
        "showpath": "Display the currently saved global path.",
        "clrpath":  "Clear the global path and return to system default.",
        "setfile":  "Create a file (and folders) and write code interactively.",
        "repl" :    "Use the repl mode of zonetic.",
        "tokens":   "Lexical analysis. Displays the stream of tokens generated by the lexer.",
        "ast":      "Syntax analysis. Visualizes the Abstract Syntax Tree (AST) after parsing.",
        "update":   "Sync with GitHub and auto-update to the latest [STABLE] version."
}

def run_cli():
    args = sys.argv[1:]
    if len(args) == 0:
        print("[zon error]: No command or file specified.")
        print("-- The forge is idle. Use zon help to learn the commands and start building.")
        return
    
    if args[0] in ['r', "run"]:
        if len(args) < 2:
            print("[zon error]: No file specified for the run command.")
            print("-- The engine needs a target. Use zon r <filename>.zon to start execution.")
            return
        
        cmd_zon_run(args[1])
    
    elif args[0] == "vers":
        cmd_zon_version()
        
    elif args[0] == "help":
        params = args[1:]
        if len(params) > 0:
            cmd_zon_help(params[0])
            return
        
        cmd_zon_help(commands=commands)
        return
    
    elif args[0] == "setpath":
        path = args[1:]
        if len(path) < 1:
            print("[zon error]: No path provided for setpath.")
            print("-- Usage: zon setpath /path/to/your/scripts")
            return
        
        cmd_zon_set_path(path[0])
        
    elif args[0] == "showpath":
        cmd_zon_show_path()
        
    elif args[0] == "clrpath":
        cmd_zon_clear_path()
        
    elif args[0] == "setfile":
        path = args[1:]
        if len(path) < 1:
            print("[zon error]: No path or filename specified.")
            print("-- Usage: zon setfile path/to/folder/script.zon")
            return
        
        cmd_zon_set_file(path[0])
        
    elif args[0] == "repl":
        cmd_zon_set_file(mode=1)
        
    elif args[0] == "tokens":
        if len(args) < 2:
            print("[zon error]: No file specified for the tokens command.")
            print("-- The engine needs a target. Use zon tokens <filename>.zon to start execution.")
            return
        
        cmd_zon_run(args[1], "token")
        
    elif args[0] == "ast":
        if len(args) < 2:
            print("[zon error]: No file specified for the ast command.")
            print("-- The engine needs a target. Use zon ast <filename>.zon to start execution.")
            return
        
        cmd_zon_run(args[1], "ast")
        
    else:
        list_commands = []
        for key in commands:
            if key == "r|run":
                list_commands.append("r")
                list_commands.append("run")
                continue
            list_commands.append(key)
        
        leven = levenshtein_zon.suggest_command(args[0], list_commands, 5)
        if leven is None: leven = "Use zon help to see the available commands."
        else: leven = leven = f"Did you mean?: {leven}"
            
        print("[zon error]: Unknown command.")
        print(f"-- The forge doesn't recognize that instruction. {leven}")