from .cmdinfo import CmdInfo, Flag, CmdArg

COMMANDS = {
    "r" : CmdInfo(
        area='r',
        summary="Run a Zonetic program (.zbc or .zon).",
        category="exe",
        usage="zon r <path>",
        args=[
            CmdArg(
                name="<path>",
                description="Path to the .zon or .zbc file to execute."
            )
        ]
    ),
    
    "c" : CmdInfo(
        area='c',
        summary="Translate source code (.zon) into bytecode (.zbc).",
        category="exe",
        usage="zon c <path>",
        args=[
            CmdArg(
                name="<path>",
                description="Path to the .zon file to compile into .zbc."
            )
        ]
    ),
    
    "repl": CmdInfo(
        area="repl",
        summary="Launch the interactive Zonetic shell.",
        category="exe",
        usage="zon repl [flag] [keyend]",
        flags=[
            Flag(
                name="--in",
                description="Run on the old interpreter"
            ),
            Flag(
                name="default",
                description="Run in the VM"
            )
        ],
        args=[
            CmdArg(
                name="[keyend]",
                description="Ends with [key] (default: EOF)."
            )
        ]
    ),
    
    "rin" : CmdInfo(
        area="rin",
        summary="Runs .zon files using the legacy interpreter engine (v0.1.6)<.",
        category="exe",
        usage="zon rin <path>",
        args=[
            CmdArg(
                name="<path>",
                description="Path to the .zon file to execute."
            )
        ]
    ),
    
    "st" : CmdInfo(
        area="st",
        summary="Configures environment variables and workspace settings for the Zonetic ecosystem.",
        category="manag",
        usage="zon st <flag> <value>",
        flags=[
            Flag(
                name="--path <dir>",
                description="Set a global directory for file searching."
            ),
            Flag(
                name="--file <path>",
                description="Create a file(.zon) (and necessary folders) and start interactive writing."
            ),
            Flag(
                name="--zbc <path>",
                description="Create a file(.zbc) (and necessary folders) and start interactive writing."
            )
        ]
    ),
    
    "vw" : CmdInfo(
        area="vw",
        summary="Displays detailed information about the system, configuration state, or code analysis.",
        category="manag",
        usage="zon vw <flag> [path]",
        flags=[
            Flag(
                name="--vers",
                description="Show current version and Zonny's greeting."
            ),
            Flag(
                name="--path",
                description="Display the currently saved global search path."
            ),
            Flag(
                name="--file <path>",
                description="Show the content of any specified file in the terminal."
            ),
            Flag(
                name="--ast <path>",
                description="Visualize the Abstract Syntax Tree of the specified file."
            ),
            Flag(
                name="--tokens <path>",
                description="Display the token stream generated by the lexer."
            )
        ]
    ),
    
    "clr": CmdInfo(
        area="clr",
        summary="Removes temporary data or resets configurations to factory defaults.",
        category="manag",
        usage="zon clr <flag>",
        flags=[
            Flag(
                name="--path",
                description="Delete the saved global path and reset to default."
            ),
            Flag(
                name="--his",
                description="Clear the command history of the REPL mode."
            )
        ]
    ),
    
    "update": CmdInfo(
        area="update",
        summary="Sync and update the entire ecosystem to the latest version.",
        category="sys",
        usage="zon update"
    ),
    
    "help" : CmdInfo(
        area="help",
        summary="Show this message or detailed info for a specific area.",
        category="sys",
        usage="zon help [area]",
        args=[
            CmdArg(
                name="[area]",
                description="Zon Cli Command"
            )
        ]
    )
    
}